### PR TITLE
Add ilp.hexdivision.com

### PR DESCRIPTION
**Pull request by h0vhannes**

### CODE REVIEW

**Comment by michielbdejong** [comment]
awesome, welcome to the Interledger! :)

**Comment by h0vhannes** [comment]
thanks :)

**Comment by michielbdejong** [comment]
My personal node is ilp-kit.michielbdejong.com, I just peered with your for 10 euros, you'll be able to see this in your peering tab as soon as you peer with me (currency: "EUR") and refresh the page - you should see me as a peer, and that should allow you to send small payments to other nodes listed on connector.land

**Comment by h0vhannes** [comment]
Thanks, I've added you as a peer.

**Pull request merged**
